### ISSUE TITLE
[FEATURE] - Stappen overslaan globaal afhandelen

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-wizard#11]
**Wat moet er gebeuren**
Een attribuut om globaal het overslaan van stappen af te zetten, bijvoorbeeld

```
<vl-wizard data-vl-skip-steps-disabled> 
```
Wanneer dit attribuut wordt gedefinieerd, is het niet mogelijk v.b. van stap 1 naar stap 3 te gaan. Iemand die de wizard gebruikt zal dus alle stappen verplicht sequentieel moeten doorlopen.

Als dit door de wizard webcomponent wordt afgehandeld:
- moet de afnemer geen custom code schrijven
- is het onmiddellijk bruikbaar voor anderen
- zit de logica centraal

**Extra info**
Nog (vrij) te beslissen:
- 1 globaal attribuut voor volgende stappen / vorige stappen. Of 2 attributen voor anders gedrag voorwaarts / terug. (Misschien wil je teruggaan van stap 3 naar 1 wel toestaan)
- cursor voor progress bar step (pointer? not-allowed?) wanneer klikken niet is toegestaan

**Comment by driesva** [comment]
@philipperutten misschien heb jij enkele bijkomende opmerkingen?

**Comment by philipperutten** [comment]
De progressbar in een wizard is normaliter niet bedoeld als navigatie naar de stappen, maar ter indicatie van de voortgang ("progress") doorheen de wizard; van wat je reeds gedaan hebt, en wat er nog te wachten staat. Op het moment dat je de progressbar als navigatie gaat gebruiken, kan dat verwarrend worden. Zeker als, zoals nu in de demo, de progressbar ook nog eens rood kleurt tot aan de stap waar je naartoe navigeert. Dit gaat dan ten koste van de eigenlijke functie, namelijk aangeven tot waar ik ben gevorderd. Er zijn dan immers al stappen 'ingekleurd' die ik nog moet invullen.
Ik zou er dan ook voor pleiten om het navigeren door de stappen dmv de progressbar standaard AF te zetten, en eventueel de mogelijkheid voorzien dit aan te zetten. (Maar niet eens per se! Je kunt je immers afvragen of voor een use case waar je vrij door 'stappen' moet kunnen navigeren, een wizard wel het meest geschikte patroon is...)
Trouwens, als ik me niet vergis is deze wizard component eigenlijk gebaseerd op een caroussel, wat dan verklaart waarom de 'progressbar' ook als navigatie fungeert: eigenlijk zijn dit namelijk de bullets waarmee je door de caroussel navigeert. Maar dat is dus een totaal ander UX patroon!!

**Comment by philipperutten** [comment]
zie ook https://www.nngroup.com/articles/wizards/
Recommendation 3: "Do not allow users to pick step before completing the steps preceding it"
