### ISSUE TITLE
[BUG] - vl-wizard-all.min.js moet vl-wizard.min.js en vl-wizard-pane.min.js gebruiken

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-wizard#14]
**Omschrijf het probleem**
Ik zie dat jullie een vl-wizard-all.min.js aanbieden, echter gebruikt deze niet de minified versie van vl-wizard en vl-wizard-pane.

Huidige inhoud van vl-wizard-all.min.js
`import{VlWizard}from"/node_modules/vl-ui-wizard/dist/vl-wizard.js";import{VlWizardPane}from"/node_modules/vl-ui-wizard/dist/vl-wizard-pane.js";export{VlWizard,VlWizardPane};
`

**Gewenst gedrag**
Ik zou verwachten dat de all.min.js de min.js versies van beiden gebruikt, dus:

`import{VlWizard}from"/node_modules/vl-ui-wizard/dist/vl-wizard.min.js";import{VlWizardPane}from"/node_modules/vl-ui-wizard/dist/vl-wizard-pane.min.js";export{VlWizard,VlWizardPane};
`

**Omgeving (gelieve aan te vullen):**
 - Versie component : 1.0.1

**Comment by driesva** [comment]
Bijkomend hierbij is dat vl-wizard.min.js een import doet van vl-wizard pane, maar ook niet de minified versie:

`import{VlElement,define}from"/node_modules/vl-ui-core/dist/vl-core.min.js";import"/node_modules/vl-ui-progress-bar/dist/vl-progress-bar.min.js";import"/node_modules/vl-ui-wizard/lib/wizard.js";import"./vl-wizard-pane.js";export class VlWizard...`

**Comment by driesva** [comment]
@coemans  ook gerelateerd aan  #160 neem ik aan?

**Comment by coemans** [comment]
Klopt, ondertussen opgelost via #24.
