### ISSUE TITLE
[BUG] - knoppen plakken aan elkaar als ze onder elkaar komen te staan

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-wizard#30]
**Omschrijf het probleem**
Wanneer de navigatie slots niet op 1 lijn passen, komen die onder elkaar en plakken ze vast aan elkaar. Wanneer de standaard vl-button-link wordt gebruikt is dit niet echt een issue, maar wel als dit een ander button is.

**Hoe te reproduceren**

```
                      <button is="vl-button" type="button" slot="next-action" secondary>
                            Naar de vorige stap gaan
                        </button>
                        <button is="vl-button" type="button" slot="next-action">
                            Naar de volgende stap gaan
                        </button>
```

**Gewenst gedrag**
Ruimte ertussen

**Screenshots**
In onze app:
![image](https://user-images.githubusercontent.com/29454303/82046121-9bc4d500-96b0-11ea-9712-63e4ee626a52.png)

Even gesimuleerd met demo:
![image](https://user-images.githubusercontent.com/29454303/82046087-88196e80-96b0-11ea-956d-e0b0efb87f0e.png)

**Omgeving (gelieve aan te vullen):**
 - Browser Fx / Chrome
 - Versie 77.0b5 (64-bit) /  81.0.4044.138
 - Versie component [vb. 1.0.14]

**Comment by coemans** [comment]
@driesva het is eigenlijk de bedoeling dat de vl-button-link gebruikt wordt, dan is er geen probleem.

**Comment by driesva** [comment]
Wel ja, maar in afwachting van de stappen te beheren via code hadden wij momenteel 1 slot "misbruikt" en ik heb dit issue zo opgemerkt.

Is minor, maar als je de afnemer de optie geeft om daar iets willekeurig te zetten, lijkt een goede weergave ook nodig.

**Comment by coemans** [comment]
Het doel van die vrijheid is hopelijk niet om af te kunnen wijken van de huisstijl. Er wordt geadviseerd om een vl-button-link te gebruiken om terug te gaan naar een vorige stap en een vl-ui-button primary variant om verder te gaan naar de volgende stap. Het doel van #26 is om in uitzonderlijke gevallen de rendering applicatief over te nemen of programmatisch te kunnen navigeren tussen stappen. Als die richtlijnen gevolgd worden, lijkt het me niet nodig om dit issue op te lossen.

Aan @kevcraey om alsnog in te plannen.

**Comment by driesva** [comment]
In ons geval gaat het over de 1ste stap, waar er dus geen "vorige" is maar enkel afmelden/ "volgende". In plaats van het slot te misbruiken zullen we de knoppen zelf definiëren conform de huisstijl.

Aan jullie de beslissing of jullie dergelijke zaken al dan niet aanpakken, ik meld gewoon maar.

**Comment by coemans** [comment]
Als het puur over de knoppen gaat los van de context van een vl-ui-wizard, is het eerder een bug voor vl-ui-action-group. Ik merk dat AIV ook last heeft van dit gedrag, maar het issue kan op dat niveau zeker aangekaart en opgelost worden.
