### ISSUE TITLE
[BUG] - bij het gebruiken van de tab wordt soms content van een inactive pane getoond

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-wizard#33]
**Omschrijf het probleem**
Soms duikt content van een inactief pane op wat natuurlijk niet kan.

**Hoe te reproduceren**
Navigeren en tabben

**Gewenst gedrag**
Tab stop die enkel op huidige actieve pane blijft.

**Screenshots**
[tab issue.mov.zip](https://github.com/milieuinfo/webcomponent-vl-ui-wizard/files/4680455/tab.issue.mov.zip)

**Omgeving (gelieve aan te vullen):**
 - Browser any
 - Versie component PR 32

**Extra info**
We gebruiken de wizard in combinatie met LitElement

**Comment by driesva** [comment]
Ik heb dit ook min/of meer kunnen reproduceren op de demo pagina (zie uiterst rechts):
![image](https://user-images.githubusercontent.com/29454303/82980195-1fec5600-9fe9-11ea-941d-1efffce6c061.png)

Een vermoeden is dat dit gebeurt omdat de panes in de DOM blijven en er nog elementen aanwezig zijn in een ander pane die een tab stop hebben.

Een analyse van de pagina zegt dan ook dat er elementen focusable zijn die niet getoond worden, vb:
![image](https://user-images.githubusercontent.com/29454303/82980323-75c0fe00-9fe9-11ea-94d2-4adca34d21f8.png)

In onze applicatie lijkt het niet meer te gebeuren omdat we nu het pane op _hidden_ zetten wanneer het inactief wordt.

**Comment by coemans** [comment]
Probleem lijkt niet meer reproduceerbaar, vermoedelijk opgelost in één van voorgaande PR's.

**Comment by driesva** [comment]
Ik kan het ook niet direct meer reproduceren, vermoedelijk gerelateerd aan #35 waardoor het inderdaad opgelost is met een bestaande PR.

Ik sluit het af en indien het zich toch nog zou voordoen, heropen ik wel.
