### ISSUE TITLE
[BUG] - Mobile: scrollen in pane X zorgt voor een leeg X+1 pane

### ISSUE THREAD

**Issue by mathiasbosman** [milieuinfo/webcomponent-vl-ui-wizard#55]
**Omschrijf het probleem**
Indien je op een smartphone in een bepaald paneel naar beneden scrollt om op "volgende" te kunnen klikken is het volgende paneel leeg.
Bij resize wordt de content wel getoond.

**Hoe te reproduceren**
Surf via een smartphone (of emuleer) met Safari / Chrome naar de wizard.
In een paneel met wat langere content scroll je naar beneden en klik je op volgende.
=> het volgende paneel is leeg.

(indien je emuleert moet je resizen om de content te doen verschijnen, op een mobiel toestel kan je gewoon even scrollen)

**Gewenst gedrag**
Het volgende paneel wordt correct getoond.

**Screenshots**
![gif-je](https://i.ibb.co/QKRHqyN/Peek-2020-07-01-10-39.gif)

**Omgeving (gelieve aan te vullen):**
 - Browser: Chrome 83 op Android 10 (of ge-emuleerd), Safari op iOS (mobiel)
 - Versie component: 1.1.2

**Comment by driesva** [comment]
Correctie ivm versie component, wij zitten op de master. Dus alle fixes (#35, #19, ...) ivm wizard zouden daar in moeten zitten.

**Comment by coemans** [comment]
Probleem is niet reproduceerbaar, vermoedelijk had de applicatie niet de laatste #master branch als dependency.

**Comment by driesva** [comment]
Net geprobeerd op onze oefen omgeving, https://loket-erkenningen-leefmilieu-oefen.omgeving.vlaanderen.be/ en het probleem doet zich nog
![Screenshot 2020-07-15 at 10 52 17](https://user-images.githubusercontent.com/29454303/87525719-2ebac500-c68a-11ea-841a-fc9245efcd48.png)
![Screenshot 2020-07-15 at 10 54 23](https://user-images.githubusercontent.com/29454303/87525728-31b5b580-c68a-11ea-8432-f988222a1139.png)
![Screenshot 2020-07-15 at 10 56 46](https://user-images.githubusercontent.com/29454303/87525733-34180f80-c68a-11ea-9268-8f5b18bfef3c.png)

**Comment by coemans** [comment]
Probleem niet meer te reproduceren bij v1.2.0.
